### ISSUE TITLE
ADIOS2 Compilation problem

### ISSUE THREAD

**Issue by kacpnowak** [martinclaus/swm#2]
Hi, 
I got a problem with compiling adios2 with fortran. I created small c++ and fortran programs for illustration. 
While C++ version works great I got following error with fortran.   

 gfortran  -DADIOS2_USE_MPI -I/usr/include/adios2/fortran  ./mini.f90
/usr/bin/ld: /tmp/cck4KFqu.o: in function `MAIN__':
mini.f90:(.text+0x33): undefined reference to `__adios2_adios_init_mod_MOD_adios2_init_serial'
/usr/bin/ld: mini.f90:(.text+0x63): undefined reference to `__adios2_adios_mod_MOD_adios2_declare_io'
/usr/bin/ld: mini.f90:(.text+0x79): undefined reference to `__adios2_adios_mod_MOD_adios2_finalize'
collect2: error: ld returned 1 exit status

I tried many different compilation flags, but they don't make any difference. 
I'd really appreciate if you could try compiling this example with adios. 

Here you can find [repo](https://github.com/pnorbert/adiosvm) with adios examples in both c++ and fortran.

**Comment by martinclaus** [comment]
Hi @Anarion19, the problem is that you need to specify two libraries to link against, the adios2 fortran bindings and adios2 fortran bindings with MPI support. The easiest way to get the correct build flags is to use the `adios2-config` executable:
```bash
gfortran $(adios2-config --mpi --fortran) ./mini.f90
```
This worked for me on Mac OSX Monterey with adios2 installed via homebrew.

**Comment by kacpnowak** [comment]
Hi @martinclaus, thank you for you help. I haven't thought that MPI support is necessary.
